- name: Import key
  shell: |
    curl -sSL https://rvm.io/mpapis.asc | gpg2 --import -
    curl -sSL https://rvm.io/pkuczynski.asc | gpg2 --import -
   
- name: downloading RVM installer
  get_url:
    url: "{{rvm.url}}"
    dest: "{{rvm.temp_installer_path}}"

- name: set executable RVM installer
  file:
    path: "{{rvm.temp_installer_path}}"
    mode: 0750

- name: installing RVM as root
  command: "{{rvm.temp_installer_path}} --path /usr/local/rvm stable"
  when: ansible_user == "root" 

- name: removing RVM installer
  file:
    path: "{{rvm.temp_installer_path}}"
    state: absent

- name: setting RVM autolibs on as root
  command: "/usr/local/rvm/bin/rvm autolibs 3"
  when: ansible_user == "root"

- name: installing Ruby as root
  command: "/usr/local/rvm/bin/rvm install {{rvm_default_ruby_version}}"

- name: setting default Ruby version as root
  shell: "source /etc/profile.d/rvm.sh && rvm use {{rvm_default_ruby_version}} --default executable=/bin/bash"
  ignore_errors: True
  changed_when: False
