 - name: Install ruby-install tool
   shell: |
     wget -O ruby-install-0.7.1.tar.gz https://github.com/postmodern/ruby-install/archive/v0.7.1.tar.gz 
     tar -xzvf ruby-install-0.7.1.tar.gz
     cd ruby-install-0.7.1/
     sudo make install


# - name: Install Bundler
#   gem:
#     name: bundler

- debug: msg="Not Support Centos"
