 - name: Install ruby-install tool
   shell: |
     wget -O ruby-install-{{ruby_rubyinstall_version}}.tar.gz https://github.com/postmodern/ruby-install/archive/v{{ruby_rubyinstall_version}}.tar.gz 
     tar -xzvf ruby-install-{{ruby_rubyinstall_version}}.tar.gz
     cd ruby-install-{{ruby_rubyinstall_version}}/
     sudo make install

 - name: Install ruby-{{ruby_version}} and bundle
   shell: |
     ruby-install ruby {{ruby_version}}
     ln -sf /opt/rubies/ruby-*/bin/ruby /usr/bin
     ln -sf /opt/rubies/ruby-*/bin/gem /usr/bin
     gem install bundle
     ln -sf /opt/rubies/ruby-*/bin/bundle /usr/bin
     ln -sf /opt/rubies/ruby-*/bin/rake /usr/bin
     ln -sf /opt/rubies/ruby-*/bin/rails /usr/bin
     ln -sf /opt/rubies/ruby-*/bin/puma /usr/local/bin
