 - name: Install ruby-install tool
   shell: |
     wget -O ruby-install-{{ruby_rubyinstall_version}}.tar.gz https://github.com/postmodern/ruby-install/archive/v{{ruby_rubyinstall_version}}.tar.gz 
     tar -xzvf ruby-install-{{ruby_rubyinstall_version}}.tar.gz
     cd ruby-install-{{ruby_rubyinstall_version}}/
     sudo make install


 - name: Install Bundler
   shell: |
     ruby-install ruby {{ruby_version}}
     ln -sf /opt/rubies/ruby-2.4.10/bin/ruby /usr/bin
