 - name: Install ruby-install tool
   shell: |
     wget -O ruby-install-{{ruby_rubyinstall_version}}.tar.gz https://github.com/postmodern/ruby-install/archive/v{{ruby_rubyinstall_version}}.tar.gz 
     tar -xzvf ruby-install-{{ruby_rubyinstall_version}}.tar.gz
     cd ruby-install-{{ruby_rubyinstall_version}}/
     sudo make install


# - name: Install Bundler
#   gem:
#     name: bundler

- debug: msg="Not Support Centos"
